sudo: required

language: python

services:
  - docker

install: true
script: true

# this trick is done to allow compiling ARM images ander x86
# here we map arm executeable header to /usr/bin/qemu-arm-static
# handler that is located in common-arm container
# by doing this, we'll have arm environment in our container
# produced from common-arm
before_script:
- sudo cat /proc/sys/fs/binfmt_misc/status
- sudo sh -c "echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' > /proc/sys/fs/binfmt_misc/register"

after_script:
- ./build.sh